<p><b>[WARN]</b>&nbsp;Retrying (RetryAdapter(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f253a86d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /produtos?nome=Non-existent%20products&</p><p><b>[WARN]</b>&nbsp;Retrying (RetryAdapter(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f253a8880>: Failed to establish a new connection: [Errno 111] Connection refused')': /produtos?nome=Non-existent%20products&</p><p><b>[WARN]</b>&nbsp;Retrying (RetryAdapter(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f253a8a90>: Failed to establish a new connection: [Errno 111] Connection refused')': /produtos?nome=Non-existent%20products&</p><p style="color: red"><b>[FAIL]</b>&nbsp;ConnectionError: HTTPConnectionPool(host='localhost', port=3030): Max retries exceeded with url: /produtos?nome=Non-existent%20products& (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f253a8ca0>: Failed to establish a new connection: [Errno 111] Connection refused'))</p>