<p><b>[WARN]</b>&nbsp;Retrying (RetryAdapter(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f2542fe80>: Failed to establish a new connection: [Errno 111] Connection refused')': /produtos?_id=K6leHdftCeOJj8BJ&</p><p><b>[WARN]</b>&nbsp;Retrying (RetryAdapter(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f2542f0d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /produtos?_id=K6leHdftCeOJj8BJ&</p><p><b>[WARN]</b>&nbsp;Retrying (RetryAdapter(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f2542f430>: Failed to establish a new connection: [Errno 111] Connection refused')': /produtos?_id=K6leHdftCeOJj8BJ&</p><p style="color: red"><b>[FAIL]</b>&nbsp;ConnectionError: HTTPConnectionPool(host='localhost', port=3030): Max retries exceeded with url: /produtos?_id=K6leHdftCeOJj8BJ& (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f2542f790>: Failed to establish a new connection: [Errno 111] Connection refused'))</p>