<p><b>[WARN]</b>&nbsp;Retrying (RetryAdapter(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbbe35e3af0>: Failed to establish a new connection: [Errno 111] Connection refused')': /usuarios</p><p><b>[WARN]</b>&nbsp;Retrying (RetryAdapter(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbbe365ddf0>: Failed to establish a new connection: [Errno 111] Connection refused')': /usuarios</p><p><b>[WARN]</b>&nbsp;Retrying (RetryAdapter(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbbe36564f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /usuarios</p><p style="color: red"><b>[FAIL]</b>&nbsp;ConnectionError: HTTPConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /usuarios (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbbe3640f40>: Failed to establish a new connection: [Errno 111] Connection refused'))</p>